language: java

sudo: required

jdk:
  - openjdk12

services:
  - docker

jobs:
  include:
    - stage: build artifact and documentation
      if: branch = master
      script:
        - "$PWD/scripts/clean-up.sh"
        - "$PWD/scripts/build-artifacts.sh || exit 101"
    - stage: test coverage
      if: branch = dev
      script:
        - "$PWD/scripts/test-coverage.sh || exit 300"
