version: "3"

services:
  db:
    image: "mariadb:10"
    environment:
        - MYSQL_ROOT_PASSWORD=Password
    ports:
        - "3306:3306"
  queue:
    image: "rabbitmq:3-management"
    environment:
        - RABBITMQ_DEFAULT_USER=root
        - RABBITMQ_DEFAULT_PASS=Password
    ports:
      - "5672:5672"
      - "15672:15672"
